import { Geist, Geist_Mono, Nunito } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar/Navbar";

const ninitoFont = Nunito({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="light"
       className={`${ninitoFont.className}  h-full antialiased`}
    >
      <body>
        <Navbar />

        <main className="bg-gray-100">
          {children}
        </main>

      </body>
    </html>
  );
}