import { Geist, Geist_Mono, Nunito } from "next/font/google";
import "./globals.css";
import 'animate.css';
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import { ToastContainer } from "react-toastify";

const ninitoFont = Nunito({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${ninitoFont.className}  h-full antialiased`}
    >
      <body>
        <Navbar />
        <main className="">
          {children}
        </main>
        <Footer />
        <ToastContainer
          position="top-center"
          autoClose={3000}
          hideProgressBar
          closeOnClick
          pauseOnHover
          theme="dark"
        />
      </body>
    </html>
  );
}